labels = [
    'label:SITTING',
    'label:FIX_walking',
    'label:COMPUTER_WORK',
    'label:OR_standing',
    # 'label:LYING_DOWN',
    # 'label:TALKING',
    # 'label:STROLLING'

]
# 46 watch acc
features = [
    'watch_acceleration:magnitude_stats:mean',
    'watch_acceleration:magnitude_stats:std',
    'watch_acceleration:magnitude_stats:moment3',
    'watch_acceleration:magnitude_stats:moment4',
    'watch_acceleration:magnitude_stats:percentile25',
    'watch_acceleration:magnitude_stats:percentile50',
    'watch_acceleration:magnitude_stats:percentile75',
    'watch_acceleration:magnitude_stats:value_entropy',
    'watch_acceleration:magnitude_stats:time_entropy',
    'watch_acceleration:magnitude_spectrum:log_energy_band0',
    'watch_acceleration:magnitude_spectrum:log_energy_band1',
    'watch_acceleration:magnitude_spectrum:log_energy_band2',
    'watch_acceleration:magnitude_spectrum:log_energy_band3',
    'watch_acceleration:magnitude_spectrum:log_energy_band4',
    'watch_acceleration:magnitude_spectrum:spectral_entropy',
    'watch_acceleration:magnitude_autocorrelation:period',
    'watch_acceleration:magnitude_autocorrelation:normalized_ac',
    'watch_acceleration:3d:mean_x',
    'watch_acceleration:3d:mean_y',
    'watch_acceleration:3d:mean_z',
    'watch_acceleration:3d:std_x',
    'watch_acceleration:3d:std_y',
    'watch_acceleration:3d:std_z',
    'watch_acceleration:3d:ro_xy',
    'watch_acceleration:3d:ro_xz',
    'watch_acceleration:3d:ro_yz',
    'watch_acceleration:spectrum:x_log_energy_band0',
    'watch_acceleration:spectrum:x_log_energy_band1',
    'watch_acceleration:spectrum:x_log_energy_band2',
    'watch_acceleration:spectrum:x_log_energy_band3',
    'watch_acceleration:spectrum:x_log_energy_band4',
    'watch_acceleration:spectrum:y_log_energy_band0',
    'watch_acceleration:spectrum:y_log_energy_band1',
    'watch_acceleration:spectrum:y_log_energy_band2',
    'watch_acceleration:spectrum:y_log_energy_band3',
    'watch_acceleration:spectrum:y_log_energy_band4',
    'watch_acceleration:spectrum:z_log_energy_band0',
    'watch_acceleration:spectrum:z_log_energy_band1',
    'watch_acceleration:spectrum:z_log_energy_band2',
    'watch_acceleration:spectrum:z_log_energy_band3',
    'watch_acceleration:spectrum:z_log_energy_band4',
    'watch_acceleration:relative_directions:avr_cosine_similarity_lag_range0',
    'watch_acceleration:relative_directions:avr_cosine_similarity_lag_range1',
    'watch_acceleration:relative_directions:avr_cosine_similarity_lag_range2',
    'watch_acceleration:relative_directions:avr_cosine_similarity_lag_range3',
    'watch_acceleration:relative_directions:avr_cosine_similarity_lag_range4',
    # 'watch_heading:mean_cos',
    # 'watch_heading:std_cos',
    # 'watch_heading:mom3_cos',
    # 'watch_heading:mom4_cos',
    # 'watch_heading:mean_sin',
    # 'watch_heading:std_sin',
    # 'watch_heading:mom3_sin',
    # 'watch_heading:mom4_sin',
    # 'watch_heading:entropy_8bins',
    # 'audio_naive:mfcc0:mean',
    # 'audio_naive:mfcc1:mean',
    # 'audio_naive:mfcc2:mean',
    # 'audio_naive:mfcc3:mean',
    # 'audio_naive:mfcc4:mean',
    # 'audio_naive:mfcc5:mean',
    # 'audio_naive:mfcc6:mean',
    # 'audio_naive:mfcc7:mean',
    # 'audio_naive:mfcc8:mean',
    # 'audio_naive:mfcc9:mean',
    # 'audio_naive:mfcc10:mean',
    # 'audio_naive:mfcc11:mean',
    # 'audio_naive:mfcc12:mean',
    # 'audio_naive:mfcc0:std',
    # 'audio_naive:mfcc1:std',
    # 'audio_naive:mfcc2:std',
    # 'audio_naive:mfcc3:std',
    # 'audio_naive:mfcc4:std',
    # 'audio_naive:mfcc5:std',
    # 'audio_naive:mfcc6:std',
    # 'audio_naive:mfcc7:std',
    # 'audio_naive:mfcc8:std',
    # 'audio_naive:mfcc9:std',
    # 'audio_naive:mfcc10:std',
    # 'audio_naive:mfcc11:std',
    # 'audio_naive:mfcc12:std',
    # 'audio_properties:max_abs_value',
    # 'audio_properties:normalization_multiplier',
    # 'raw_acc:magnitude_stats:mean',
    # 'raw_acc:magnitude_stats:std',
    # 'raw_acc:magnitude_stats:moment3',
    # 'raw_acc:magnitude_stats:moment4',
    # 'raw_acc:magnitude_stats:percentile25',
    # 'raw_acc:magnitude_stats:percentile50',
    # 'raw_acc:magnitude_stats:percentile75',
    # 'raw_acc:magnitude_stats:value_entropy',
    # 'raw_acc:magnitude_stats:time_entropy',
    # 'raw_acc:magnitude_spectrum:log_energy_band0',
    # 'raw_acc:magnitude_spectrum:log_energy_band1',
    # 'raw_acc:magnitude_spectrum:log_energy_band2',
    # 'raw_acc:magnitude_spectrum:log_energy_band3',
    # 'raw_acc:magnitude_spectrum:log_energy_band4',
    # 'raw_acc:magnitude_spectrum:spectral_entropy',
    # 'raw_acc:magnitude_autocorrelation:period',
    # 'raw_acc:magnitude_autocorrelation:normalized_ac',
    # 'raw_acc:3d:mean_x',
    # 'raw_acc:3d:mean_y',
    # 'raw_acc:3d:mean_z',
    # 'raw_acc:3d:std_x',
    # 'raw_acc:3d:std_y',
    # 'raw_acc:3d:std_z',
    # 'raw_acc:3d:ro_xy',
    # 'raw_acc:3d:ro_xz',
    # 'raw_acc:3d:ro_yz',
    # 'proc_gyro:magnitude_stats:mean',
    # 'proc_gyro:magnitude_stats:std',
    # 'proc_gyro:magnitude_stats:moment3',
    # 'proc_gyro:magnitude_stats:moment4',
    # 'proc_gyro:magnitude_stats:percentile25',
    # 'proc_gyro:magnitude_stats:percentile50',
    # 'proc_gyro:magnitude_stats:percentile75',
    # 'proc_gyro:magnitude_stats:value_entropy',
    # 'proc_gyro:magnitude_stats:time_entropy',
    # 'proc_gyro:magnitude_spectrum:log_energy_band0',
    # 'proc_gyro:magnitude_spectrum:log_energy_band1',
    # 'proc_gyro:magnitude_spectrum:log_energy_band2',
    # 'proc_gyro:magnitude_spectrum:log_energy_band3',
    # 'proc_gyro:magnitude_spectrum:log_energy_band4',
    # 'proc_gyro:magnitude_spectrum:spectral_entropy',
    # 'proc_gyro:magnitude_autocorrelation:period',
    # 'proc_gyro:magnitude_autocorrelation:normalized_ac',
    # 'proc_gyro:3d:mean_x',
    # 'proc_gyro:3d:mean_y',
    # 'proc_gyro:3d:mean_z',
    # 'proc_gyro:3d:std_x',
    # 'proc_gyro:3d:std_y',
    # 'proc_gyro:3d:std_z',
    # 'proc_gyro:3d:ro_xy',
    # 'proc_gyro:3d:ro_xz',
    # 'proc_gyro:3d:ro_yz',
]

